services:
  itadaki_web:
    image: ghcr.io/${REPO_OWNER}/itadaki-web@${IMAGE_DIGEST}
    expose:
      - "3000"           # expose to other containers, but no host binding
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8083:80"
    depends_on:
      - itadaki_web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

  db:
    image: postgres:17.5
    volumes:
      - itadaki_pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

volumes:
  itadaki_pgdata: