services:
  itadaki_web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"           # expose to other containers, but no host binding
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8083:80"
    depends_on:
      - itadaki_web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

  db:
    image: postgres:17.5
    volumes:
      - itadaki_pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always

volumes:
  itadaki_pgdata: