import { z } from "zod";

export const foodTemplateSchema = z.object({
  name: z.string().min(1, "Name is required"),
  brand: z.string().nullable().optional(),
  servingSize: z.coerce.number({ required_error: "Serving size is required" }),
  servingUnit: z.string().min(1, "Serving unit is required"),
  barCode: z.string().nullable().optional(),
  calories: z.coerce.number({ required_error: "Calories are required" }),
  protein: z.coerce.number().nullable().optional(),
  carbs: z.coerce.number().nullable().optional(),
  sugar: z.coerce.number().nullable().optional(),
  fiber: z.coerce.number().nullable().optional(),
  fat: z.coerce.number().nullable().optional(),
  saturatedFat: z.coerce.number().nullable().optional(),
  transFat: z.coerce.number().nullable().optional(),
  cholesterol: z.coerce.number().nullable().optional(),
  sodium: z.coerce.number().nullable().optional(),
  potassium: z.coerce.number().nullable().optional(),
  vitaminA: z.coerce.number().nullable().optional(),
  vitaminC: z.coerce.number().nullable().optional(),
  vitaminD: z.coerce.number().nullable().optional(),
  vitaminE: z.coerce.number().nullable().optional(),
  vitaminK: z.coerce.number().nullable().optional(),
  vitaminB1: z.coerce.number().nullable().optional(),
  vitaminB2: z.coerce.number().nullable().optional(),
  vitaminB3: z.coerce.number().nullable().optional(),
  vitaminB5: z.coerce.number().nullable().optional(),
  vitaminB6: z.coerce.number().nullable().optional(),
  vitaminB7: z.coerce.number().nullable().optional(),
  vitaminB9: z.coerce.number().nullable().optional(),
  vitaminB12: z.coerce.number().nullable().optional(),
  calcium: z.coerce.number().nullable().optional(),
  iron: z.coerce.number().nullable().optional(),
  magnesium: z.coerce.number().nullable().optional(),
  phosphorus: z.coerce.number().nullable().optional(),
  zinc: z.coerce.number().nullable().optional(),
  copper: z.coerce.number().nullable().optional(),
  manganese: z.coerce.number().nullable().optional(),
  selenium: z.coerce.number().nullable().optional(),
  alcohol: z.coerce.number().nullable().optional(),
  caffeine: z.coerce.number().nullable().optional(),
});

export type FoodTemplateFormData = z.infer<typeof foodTemplateSchema>;
