name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker compose -f docker-compose.prod.yml build

      - name: Start new containers
        run: docker compose -f docker-compose.prod.yml up -d --build --remove-orphans

      - name: Clean up Docker
        run: docker system prune -af
