name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push"]
    types:
      - completed

jobs:
  cancel_previous_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted]

    steps:
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull latest Docker image
        run: docker pull ghcr.io/${{ github.repository_owner }}/itadaki-web:latest

      - name: Create .env file
        run: |
          cat <<EOF > .env
          GITHUB_ID=${{ secrets.NEXTAUTH_GITHUB_ID }}
          GITHUB_SECRET=${{ secrets.NEXTAUTH_GITHUB_SECRET }}
          NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
          DB_NAME=${{ vars.DB_NAME }}
          DB_USER=${{ vars.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          POSTGRES_DB=${{ vars.DB_NAME }}
          POSTGRES_USER=${{ vars.DB_USER }}
          POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}
          SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_SENTRY_DSN=${{ vars.NEXT_PUBLIC_SENTRY_DSN }}
          SERVER_SENTRY_DSN=${{ vars.SERVER_SENTRY_DSN }}
          NEXTAUTH_URL=https://itadaki.app
          EOF

      - name: Set REPO_OWNER
        run: echo "REPO_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV

      - name: Start containers using pulled image
        run: docker compose --env-file .env -f docker-compose.prod.yml up -d --remove-orphans

      - name: Clean up unused Docker resources
        run: docker system prune -af
